In [116]:
import extract

In [117]:
import pandas as pd
from sqlalchemy import create_engine, text


username = 'root'
password = ''
host = '127.0.0.1'
database = 'music'

## Load Data ##




## Retrive Data ##
engine = create_engine(f"mysql+mysqlconnector://{username}:{password}@{host}")

with engine.connect() as connection:
    
    connection.execute(text(f"USE {database}"))
    
    query = "select * from raw_data"
    df1 = pd.read_sql(query,connection)
    connection.close()

df1.head(15)

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6
5,Sprinter,"Dave, Central Cee",2,2023,6,1,2186,91,183706234,67,...,141,C#,Major,92,66,58,19,0,8,24
6,Ella Baila Sola,"Eslabon Armado, Peso Pluma",2,2023,3,16,3090,50,725980112,34,...,148,F,Minor,67,83,76,48,0,8,3
7,Columbia,Quevedo,1,2023,7,7,714,43,58149378,25,...,100,F,Major,67,26,71,37,0,11,4
8,fukumean,Gunna,1,2023,5,15,1096,83,95217315,60,...,130,C#,Minor,85,22,62,12,0,28,9
9,La Bebe - Remix,"Peso Pluma, Yng Lvcas",2,2023,3,17,2953,44,553634067,49,...,170,D,Minor,81,56,48,21,0,8,33
10,un x100to,"Bad Bunny, Grupo Frontera",2,2023,4,17,2876,40,505671438,41,...,83,F#,Minor,57,56,72,23,0,27,5
11,Super Shy,NewJeans,1,2023,7,7,422,55,58255150,37,...,150,F,Minor,78,52,82,18,0,15,7
12,Flowers,Miley Cyrus,1,2023,1,12,12211,115,1316855716,300,...,118,None,Major,71,65,68,6,0,3,7
13,Daylight,David Kushner,1,2023,4,14,3528,98,387570742,80,...,130,D,Minor,51,32,43,83,0,9,3
14,As It Was,Harry Styles,1,2022,3,31,23575,130,2513188493,403,...,174,F#,Minor,52,66,73,34,0,31,6

In [118]:
df1.count()

track_name              953
artist(s)_name          953
artist_count            953
released_year           953
released_month          953
released_day            953
in_spotify_playlists    953
in_spotify_charts       953
streams                 953
in_apple_playlists      953
in_apple_charts         953
in_deezer_playlists     953
in_deezer_charts        953
in_shazam_charts        903
bpm                     953
key                     858
mode                    953
danceability_%          953
valence_%               953
energy_%                953
acousticness_%          953
instrumentalness_%      953
liveness_%              953
speechiness_%           953
dtype: int64

In [119]:
df1.describe()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
count,953,953,953,953,953,953,953,953,953,953,...,953,858,953,953,953,953,953,953,953,953
unique,943,645,8,50,12,31,879,82,949,234,...,124,11,2,72,94,80,98,39,68,48
top,Daylight,Taylor Swift,1,2022,1,1,1150,0,723894473,0,...,120,C#,Major,70,24,74,0,0,11,4
freq,2,34,587,402,134,95,3,405,2,23,...,39,120,550,43,21,29,60,866,102,175

In [120]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 953 entries, 0 to 952
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   track_name            953 non-null    object
 1   artist(s)_name        953 non-null    object
 2   artist_count          953 non-null    object
 3   released_year         953 non-null    object
 4   released_month        953 non-null    object
 5   released_day          953 non-null    object
 6   in_spotify_playlists  953 non-null    object
 7   in_spotify_charts     953 non-null    object
 8   streams               953 non-null    object
 9   in_apple_playlists    953 non-null    object
 10  in_apple_charts       953 non-null    object
 11  in_deezer_playlists   953 non-null    object
 12  in_deezer_charts      953 non-null    object
 13  in_shazam_charts      903 non-null    object
 14  bpm                   953 non-null    object
 15  key                   858 non-null    object
 16  mode                  953 non-null    object
 17  danceability_%        953 non-null    object
 18  valence_%             953 non-null    object
 19  energy_%              953 non-null    object
 20  acousticness_%        953 non-null    object
 21  instrumentalness_%    953 non-null    object
 22  liveness_%            953 non-null    object
 23  speechiness_%         953 non-null    object
dtypes: object(24)
memory usage: 178.8+ KB

In [121]:
df1['key'].unique()

array(['B', 'C#', 'F', 'A', 'D', 'F#', None, 'G#', 'G', 'E', 'A#', 'D#'],
      dtype=object)

In [122]:
df1[df1['key'].isnull()]

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
12,Flowers,Miley Cyrus,1,2023,1,12,12211,115,1316855716,300,...,118,None,Major,71,65,68,6,0,3,7
17,What Was I Made For? [From The Motion Picture ...,Billie Eilish,1,2023,7,13,873,104,30546883,80,...,78,None,Major,44,14,9,96,0,10,3
22,I Wanna Be Yours,Arctic Monkeys,1,2013,1,1,12859,110,1297026226,24,...,135,None,Minor,48,44,42,12,2,11,3
35,Los del Espacio,"Big One, Duki, Lit Killah, Maria Becerra, FMK,...",8,2023,6,1,1150,31,123122413,22,...,120,None,Major,81,63,68,11,0,11,4
44,Barbie World (with Aqua) [From Barbie The Album],"Nicki Minaj, Aqua, Ice Spice",3,2023,6,23,1117,80,65156199,82,...,144,None,Major,77,75,58,52,0,23,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
899,Hold Me Closer,"Elton John, Britney Spears",2,2017,11,10,4967,0,284216603,165,...,126,None,Major,67,49,77,11,0,19,11
901,After LIKE,IVE,1,2022,8,22,767,12,265548837,20,...,125,None,Major,68,80,92,10,0,9,12
903,B.O.T.A. (Baddest Of Them All) - Edit,"Interplanetary Criminal, Eliza Rose",2,2022,6,15,5153,6,244585109,102,...,137,None,Major,74,71,89,24,61,15,5
938,Labyrinth,Taylor Swift,1,2022,10,21,1597,0,187339835,6,...,110,None,Major,48,15,31,80,22,12,4
940,Sweet Nothing,Taylor Swift,1,2022,10,21,1747,0,186104310,9,...,177,None,Major,34,39,16,97,0,12,5

In [123]:
df1.isnull().any().any()

True

In [124]:
df1.isnull().any()

track_name              False
artist(s)_name          False
artist_count            False
released_year           False
released_month          False
released_day            False
in_spotify_playlists    False
in_spotify_charts       False
streams                 False
in_apple_playlists      False
in_apple_charts         False
in_deezer_playlists     False
in_deezer_charts        False
in_shazam_charts         True
bpm                     False
key                      True
mode                    False
danceability_%          False
valence_%               False
energy_%                False
acousticness_%          False
instrumentalness_%      False
liveness_%              False
speechiness_%           False
dtype: bool

In [125]:
df1.isnull().sum()

track_name               0
artist(s)_name           0
artist_count             0
released_year            0
released_month           0
released_day             0
in_spotify_playlists     0
in_spotify_charts        0
streams                  0
in_apple_playlists       0
in_apple_charts          0
in_deezer_playlists      0
in_deezer_charts         0
in_shazam_charts        50
bpm                      0
key                     95
mode                     0
danceability_%           0
valence_%                0
energy_%                 0
acousticness_%           0
instrumentalness_%       0
liveness_%               0
speechiness_%            0
dtype: int64

In [126]:
df = df1.copy(deep=True)

In [127]:
# artist_count
df['artist_count']=pd.to_numeric(df['artist_count'], errors='coerce')
# released_year
df['released_year']=pd.to_numeric(df['released_year'], errors='coerce')
# released_month
df['released_month']=pd.to_numeric(df['released_month'], errors='coerce')
# released_day
df['released_day']=pd.to_numeric(df['released_day'], errors='coerce')
# in_spotify_playlists
df['in_spotify_playlists']=pd.to_numeric(df['in_spotify_playlists'], errors='coerce')
# in_spotify_charts
df['in_spotify_charts']=pd.to_numeric(df['in_spotify_charts'], errors='coerce')
# streams
df['streams']=pd.to_numeric(df['streams'].str.replace(',', ''), errors='coerce')
# in_apple_playlists
df['in_apple_playlists']=pd.to_numeric(df['in_apple_playlists'], errors='coerce')
# in_apple_charts
df['in_apple_charts']=pd.to_numeric(df['in_apple_charts'], errors='coerce')
# in_deezer_playlists
df['in_deezer_playlists']=pd.to_numeric(df['in_deezer_playlists'].str.replace(',', ''), errors='coerce')
# in_deezer_charts
df['in_deezer_charts']=pd.to_numeric(df['in_deezer_charts'], errors='coerce')
# in_shazam_charts
df['in_shazam_charts']=pd.to_numeric(df['in_shazam_charts'], errors='coerce')
# bpm
df['bpm']=pd.to_numeric(df['bpm'], errors='coerce')
# danceability_%
df['danceability_%']=pd.to_numeric(df['danceability_%'], errors='coerce')
# valence_%
df['valence_%']=pd.to_numeric(df['valence_%'], errors='coerce')
# energy_%
df['energy_%']=pd.to_numeric(df['energy_%'], errors='coerce')
# acousticness_%
df['acousticness_%']=pd.to_numeric(df['acousticness_%'], errors='coerce')
# instrumentalness_%
df['instrumentalness_%']=pd.to_numeric(df['instrumentalness_%'], errors='coerce')
# liveness_%
df['liveness_%']=pd.to_numeric(df['liveness_%'], errors='coerce')
# speechiness_%
df['speechiness_%']=pd.to_numeric(df['speechiness_%'], errors='coerce')

In [128]:
df.describe()

,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,in_apple_charts,in_deezer_playlists,in_deezer_charts,in_shazam_charts,bpm,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
count,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000,9.520000e+02,953.000000,953.000000,953.000000,953.000000,896.000000,953.000000,953.00000,953.000000,953.000000,953.000000,953.000000,953.000000,953.000000
mean,1.556139,2018.238195,6.033578,13.930745,5200.124869,12.009444,5.141374e+08,67.812172,51.908709,385.187828,2.666317,51.176339,122.540399,66.96957,51.431270,64.279119,27.057712,1.581322,18.213012,10.131165
std,0.893044,11.116218,3.566435,9.201949,7897.608990,19.575992,5.668569e+08,86.441493,50.630241,1130.535561,6.035599,126.487856,28.057802,14.63061,23.480632,16.550526,25.996077,8.409800,13.711223,9.912888
min,1.000000,1930.000000,1.000000,1.000000,31.000000,0.000000,2.762000e+03,0.000000,0.000000,0.000000,0.000000,0.000000,65.000000,23.00000,4.000000,9.000000,0.000000,0.000000,3.000000,2.000000
25%,1.000000,2020.000000,3.000000,6.000000,875.000000,0.000000,1.416362e+08,13.000000,7.000000,13.000000,0.000000,0.000000,100.000000,57.00000,32.000000,53.000000,6.000000,0.000000,10.000000,4.000000
50%,1.000000,2022.000000,6.000000,13.000000,2224.000000,3.000000,2.905309e+08,34.000000,38.000000,44.000000,0.000000,2.000000,121.000000,69.00000,51.000000,66.000000,18.000000,0.000000,12.000000,6.000000
75%,2.000000,2022.000000,9.000000,22.000000,5542.000000,16.000000,6.738690e+08,88.000000,87.000000,164.000000,2.000000,36.000000,140.000000,78.00000,70.000000,77.000000,43.000000,0.000000,24.000000,11.000000
max,8.000000,2023.000000,12.000000,31.000000,52898.000000,147.000000,3.703895e+09,672.000000,275.000000,12367.000000,58.000000,953.000000,206.000000,96.00000,97.000000,97.000000,97.000000,91.000000,97.000000,64.000000

In [129]:
df['in_shazam_charts']=df['in_shazam_charts'].fillna(0)
df['key']=df['key'].fillna('NA')

In [130]:
df.isnull().sum()

track_name              0
artist(s)_name          0
artist_count            0
released_year           0
released_month          0
released_day            0
in_spotify_playlists    0
in_spotify_charts       0
streams                 1
in_apple_playlists      0
in_apple_charts         0
in_deezer_playlists     0
in_deezer_charts        0
in_shazam_charts        0
bpm                     0
key                     0
mode                    0
danceability_%          0
valence_%               0
energy_%                0
acousticness_%          0
instrumentalness_%      0
liveness_%              0
speechiness_%           0
dtype: int64

In [131]:
df[df['streams'].isna()].streams

574   NaN
Name: streams, dtype: float64

In [132]:
df1[df['streams'].isna()]

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
574,Love Grows (Where My Rosemary Goes),Edison Lighthouse,1,1970,1,1,2877,0,BPM110KeyAModeMajorDanceability53Valence75Ener...,16,...,110,A,Major,53,75,69,7,0,17,3

In [133]:
df['streams']=df['streams'].fillna(0)

In [134]:
df.isnull().sum()

track_name              0
artist(s)_name          0
artist_count            0
released_year           0
released_month          0
released_day            0
in_spotify_playlists    0
in_spotify_charts       0
streams                 0
in_apple_playlists      0
in_apple_charts         0
in_deezer_playlists     0
in_deezer_charts        0
in_shazam_charts        0
bpm                     0
key                     0
mode                    0
danceability_%          0
valence_%               0
energy_%                0
acousticness_%          0
instrumentalness_%      0
liveness_%              0
speechiness_%           0
dtype: int64

In [135]:
# import numpy as np
# df[df.is_numeric()]
# np.isinf(df['in_deezer_playlists'])

In [136]:
df.replace([float('inf'), float('-inf')], 0, inplace=True)

In [137]:
from sqlalchemy import create_engine

def load_csv_to_mysql(csv_path, table_name, connection_string):
    engine = create_engine(connection_string)
    # df = pd.read_csv(csv_path, encoding='Latin')
    with engine.connect() as conn:
        df.to_sql(table_name, conn, if_exists='replace', index=False)
    print(f"Data loaded into {table_name} table successfully")

# Example usage
csv_path = '/Users/mamathaputta/Documents/selfGrowth/Acedemic/projects/py sql tableau/data/spotify-2023.csv'
table_name = 'transformed_data'
connection_string = 'mysql+mysqlconnector://root:@127.0.0.1:3306/music'

load_csv_to_mysql(csv_path, table_name, connection_string)

Data loaded into transformed_data table successfully

In [114]:
#### REPORTING: just for sample

In [ ]:
# https://www.kaggle.com/code/teranekerimova/exploring-spotify-data-through-visualizations#Question-1:-top-5-songs-and-their-artists

In [113]:
# importing the necessary libraries
import matplotlib.pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

In [ ]:
top_songs_and_artists= df[['track_name','artist(s)_name','streams']].sort_values(by='streams',ascending=False).head()
top_songs_and_artists
#top songs and artists

In [ ]:
# Set the style
sns.set(style="whitegrid")
fig, ax = plt.subplots(figsize=(10, 6))
bars = sns.barplot(
    x='streams', 
    y='track_name', 
    data=top_songs_and_artists, 
    palette="viridis", 
    edgecolor='black'
)

# Add annotations
for bar in bars.patches:
    plt.annotate(
        format(bar.get_width(), ','),
        (bar.get_width(), bar.get_y() + bar.get_height() / 2),
        ha='center', 
        va='center',
        xytext=(5, 0),
        textcoords='offset points'
    )

# Set titles and labels
ax.set_title("Top 5 Songs and The Artists", fontsize=16, weight='bold')
ax.set_xlabel("Number of Streams", fontsize=14)
ax.set_ylabel("Tracks' Names", fontsize=14)

# Remove the top and right spines
sns.despine(left=True, bottom=True)

# Show the plot
plt.show()

In [ ]:
import plotly.express as px

# Create the plot
fig = px.bar(
    top_songs_and_artists, 
    x='streams', 
    y='track_name', 
    text='streams', 
    color='streams', 
    color_continuous_scale='viridis', 
    title="Top 5 Songs and The Artists"
)

# Update the layout
fig.update_layout(
    xaxis_title="Number of Streams",
    yaxis_title="Tracks' Names",
    title_font_size=22,
    title_font_family="Arial",
    xaxis=dict(showgrid=False),
    yaxis=dict(showgrid=False)
)

# Update the traces
fig.update_traces(texttemplate='%{text:,}', textposition='outside')

# Show the plot
fig.show()

In [ ]:
# Question 2: Number of songs over year on Spotify

In [ ]:
year_song= df.groupby('released_year')['track_name'].count()
year_song

In [ ]:
# Set the style
sns.set(style="whitegrid")

# First plot: Number of songs over years
fig, ax1 = plt.subplots(figsize=(12, 6))
ax1.plot(year_song.index, year_song.values, marker='o', linestyle='-', color='green', label='All years')

ax1.set_xlabel("Released Years", fontsize=14)
ax1.set_ylabel("Number of Tracks", fontsize=14)
ax1.set_title("Released Songs Over Years on Spotify", fontsize=16, weight='bold')
ax1.legend()